spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/HuseyinBilge/config-server-rentacar
server:
  port: 8888